changing gate

diff --git a/.cloudbees/workflows/demo-workflow.yaml b/.cloudbees/workflows/demo-workflow.yaml
--- a/.cloudbees/workflows/demo-workflow.yaml
+++ b/.cloudbees/workflows/demo-workflow.yaml
@@ -28,11 +28,19 @@ jobs:
             - Low: **${{ steps.blackduck-scan.outputs.low-count }}**
 
       - name: Security gate
-        if: steps.blackduck-scan.outputs.critical-count > 0 || steps.blackduck-scan.outputs.very-high-count > 0
+        if: steps.blackduck-scan.outputs.critical-count > 0
+        # if: steps.blackduck-scan.outputs.critical-count > 0 || steps.blackduck-scan.outputs.very-high-count > 0
         uses: docker://alpine:3.20
         run: |
-          echo "Security gate failed due to ${{ steps.blackduck-scan.outputs.critical-count }} critical and ${{ steps.blackduck-scan.outputs.very-high-count }} very high vulnerabilities"
-          exit 1
+          if [ ${{ steps.blackduck-scan.outputs.critical-count }} -gt 0 ]; then 
+            echo "Security gate failed due to ${{ steps.blackduck-scan.outputs.critical-count }} critical vulnerabilities"
+            exit 1
+          fi
+          # if [ ${{ steps.blackduck-scan.outputs.very-high-count }} -gt 0 ]; then
+          #   echo "Security gate failed due to ${{ steps.blackduck-scan.outputs.very-high-count }} very high vulnerabilities"
+          #   exit 1
+          # fi
+          echo "Security gate passed"
   build:
     needs:
       - scan
